" Enable new vim features since vi
set nocompatible

" Set line numbers and relative numbers
set number
set relativenumber

" Enable cursor line for better visibility
set cursorline

" Allow backspacing over indentation, line breaks, insertion
set backspace=indent,eol,start

set showcmd
set showmode
set autoread
set hidden

" UI improvements
set laststatus=2
set ruler
set wildmenu
set visualbell
colorscheme murphy
set nowrap

" Editing
set autoindent

" Smart auto indentation
filetype plugin indent on

" Highlight while the search is being input
set incsearch
set hlsearch

" Number of spaces to interpret a tab character
set tabstop=4

" Width of manual indentation
set shiftwidth=4

" Expand the new tab insertions to spaces
set expandtab

" Syntax coloring
syntax on
